# Generated by Django 4.1.1 on 2022-10-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_rename_fecha_nacimiento_persona_fecha_consulta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Person',
        ),
    ]
