# Generated by Django 4.1.1 on 2022-10-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_rename_persona_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='edad',
            new_name='Nrofav',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='fecha_consulta',
            new_name='fecha_nac',
        ),
    ]
